<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Diagnostics.FastSerialization">
      <HintPath>../tools/.store/dotnet-trace/10.0.731102/dotnet-trace/10.0.731102/tools/net8.0/any/Microsoft.Diagnostics.FastSerialization.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Diagnostics.Tracing.TraceEvent">
      <HintPath>../tools/.store/dotnet-trace/10.0.731102/dotnet-trace/10.0.731102/tools/net8.0/any/Microsoft.Diagnostics.Tracing.TraceEvent.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
