using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using SpectraEngine.Physics.Box3D;
using SpectraEngine.Physics.Box3D.Native;

namespace SpectraEngine.Physics.Tests;

/// <summary>
/// The ABI guard: every managed struct that mirrors a Box3D one is checked,
/// field by field, against a manifest generated from the C compiler itself.
/// </summary>
// The manifest is generated by native/abi-probe and committed, so this needs no
// C toolchain and no native library. Regenerate it when the submodule pin moves.
// Function signatures are not checked.
public sealed class Box3DAbiTests
{
    private static readonly Lazy<AbiManifest> Manifest = new(LoadManifest);

    [Fact]
    public void The_manifest_describes_the_build_we_actually_ship()
    {
        AbiManifest m = Manifest.Value;

        m.Precision.ShouldBe("float", "BOX3D_DOUBLE_PRECISION is off by decision, and the flag is ABI-affecting");
        m.PointerSize.ShouldBe(IntPtr.Size, "the manifest was generated for a different word size than this test runs at");
        m.Structs.ShouldNotBeEmpty();
    }

    [Theory]
    [InlineData(typeof(B3Version), "b3Version")]
    [InlineData(typeof(B3Vec3), "b3Vec3")]
    [InlineData(typeof(B3Quat), "b3Quat")]
    [InlineData(typeof(B3Transform), "b3Transform")]
    [InlineData(typeof(B3Pos), "b3Pos")]
    [InlineData(typeof(B3WorldTransform), "b3WorldTransform")]
    [InlineData(typeof(B3WorldId), "b3WorldId")]
    [InlineData(typeof(B3BodyId), "b3BodyId")]
    [InlineData(typeof(B3ShapeId), "b3ShapeId")]
    [InlineData(typeof(B3Capacity), "b3Capacity")]
    [InlineData(typeof(B3WorldDef), "b3WorldDef")]
    [InlineData(typeof(B3MotionLocks), "b3MotionLocks")]
    [InlineData(typeof(B3BodyDef), "b3BodyDef")]
    [InlineData(typeof(B3Filter), "b3Filter")]
    [InlineData(typeof(B3SurfaceMaterial), "b3SurfaceMaterial")]
    [InlineData(typeof(B3ShapeDef), "b3ShapeDef")]
    [InlineData(typeof(B3Aabb), "b3AABB")]
    public void A_managed_struct_matches_its_native_layout(Type managed, string nativeName)
    {
        AbiManifest m = Manifest.Value;
        m.Structs.ShouldContainKey(nativeName, $"the manifest has no entry for '{nativeName}'");
        NativeStruct native = m.Structs[nativeName];

        Marshal.SizeOf(managed).ShouldBe(
            native.Size,
            $"{managed.Name} is {Marshal.SizeOf(managed)} bytes but native {nativeName} is {native.Size}");

        System.Reflection.FieldInfo[] fields =
            managed.GetFields(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);

        fields.Length.ShouldBe(
            native.Fields.Count,
            $"{managed.Name} has {fields.Length} fields but native {nativeName} has {native.Fields.Count}");

        for (int i = 0; i < fields.Length; i++)
        {
            // Positional, not by name: order decides the layout.
            NativeField expected = native.Fields[i];
            int actualOffset = (int)Marshal.OffsetOf(managed, fields[i].Name);

            actualOffset.ShouldBe(
                expected.Offset,
                $"{managed.Name}.{fields[i].Name} sits at offset {actualOffset}, " +
                $"but native {nativeName}.{expected.Name} sits at {expected.Offset}");

            int actualSize = SizeOfField(fields[i].FieldType);
            actualSize.ShouldBe(
                expected.Size,
                $"{managed.Name}.{fields[i].Name} is {actualSize} bytes, " +
                $"but native {nativeName}.{expected.Name} is {expected.Size}");
        }
    }

    // Marshal.SizeOf refuses enum types, so measure the underlying integer.
    private static int SizeOfField(Type type) =>
        type.IsEnum ? Marshal.SizeOf(Enum.GetUnderlyingType(type)) : Marshal.SizeOf(type);

    [Fact]
    public void The_managed_hull_limits_match_the_ones_the_library_enforces()
    {
        // BrushHullBuilder pre-checks a brush before calling the library, so
        // its constants are a second copy of the library's.
        AbiManifest m = Manifest.Value;

        BrushHullBuilder.MaxVertices.ShouldBe(m.Limits["maxHullVertices"]);
        BrushHullBuilder.MaxFaces.ShouldBe(m.Limits["maxHullFaces"]);
        BrushHullBuilder.MaxEdges.ShouldBe(m.Limits["maxHullEdges"]);

        // Euler for a convex polyhedron: V - E + F = 2, so E = V + F - 2.
        BrushHullBuilder.MaxVerticesPlusFaces.ShouldBe(m.Limits["maxHullEdges"] + 2);
    }

    [Fact]
    public void The_guard_would_actually_catch_a_wrong_layout()
    {
        // The wrong struct swaps a ushort pair for two ints.
        AbiManifest m = Manifest.Value;
        NativeStruct native = m.Structs["b3WorldId"];

        Marshal.SizeOf<DeliberatelyWrongWorldId>().ShouldNotBe(native.Size);
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct DeliberatelyWrongWorldId
    {
        public int Index1;
        public int Generation;
    }

    private sealed record NativeField(string Name, int Offset, int Size);

    private sealed record NativeStruct(string Name, int Size, int Align, List<NativeField> Fields);

    private sealed record AbiManifest(
        string Version, string Precision, int PointerSize,
        Dictionary<string, NativeStruct> Structs, Dictionary<string, int> Limits);

    private static AbiManifest LoadManifest()
    {
        string path = FindManifest();
        string version = "", precision = "";
        int pointerSize = 0;
        var structs = new Dictionary<string, NativeStruct>(StringComparer.Ordinal);
        var limits = new Dictionary<string, int>(StringComparer.Ordinal);
        NativeStruct? current = null;

        foreach (string raw in File.ReadLines(path))
        {
            string line = raw.Trim();
            if (line.Length == 0 || line.StartsWith('#'))
                continue;

            string[] parts = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            switch (parts[0])
            {
                case "version":
                    version = parts[1];
                    break;
                case "precision":
                    precision = parts[1];
                    break;
                case "pointer":
                    pointerSize = ParseTagged(parts, "size=");
                    break;
                case "struct":
                    current = new NativeStruct(parts[1], ParseTagged(parts, "size="), ParseTagged(parts, "align="), []);
                    structs[current.Name] = current;
                    break;
                case "limit":
                    limits[parts[1]] = ParseTagged(parts, "value=");
                    break;
                case "field":
                    current.ShouldNotBeNull($"manifest has a field line before any struct line: '{line}'");
                    current!.Fields.Add(new NativeField(parts[1], ParseTagged(parts, "offset="), ParseTagged(parts, "size=")));
                    break;
                default:
                    throw new InvalidDataException($"Unrecognised manifest line: '{line}'");
            }
        }

        return new AbiManifest(version, precision, pointerSize, structs, limits);
    }

    private static int ParseTagged(string[] parts, string tag)
    {
        foreach (string part in parts)
        {
            if (part.StartsWith(tag, StringComparison.Ordinal))
                return int.Parse(part[tag.Length..], CultureInfo.InvariantCulture);
        }

        throw new InvalidDataException($"Manifest line is missing '{tag}': {string.Join(' ', parts)}");
    }

    // A missing manifest throws instead of skipping: a guard that opts out
    // when its data is gone leaves the build green.
    private static string FindManifest()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            string candidate = Path.Combine(dir.FullName, "native", "box3d-abi.manifest");
            if (File.Exists(candidate))
                return candidate;
            dir = dir.Parent;
        }

        throw new FileNotFoundException(
            "Could not find native/box3d-abi.manifest walking up from " +
            $"'{AppContext.BaseDirectory}'. It is generated by the ABI probe and committed — " +
            "regenerate it with: native/build-box3d.ps1 -Abi");
    }
}
